name: Build & deploy

on:
    push:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            - name: Install NPM packages
              run: npm ci

            - name: ESLint
              run: npm run eslint:check

            - name: Stylelint
                if: success()
                run: npm run stylelint:check

            - name: Prettier
                if: success()
                run: npm run prettier:check

            - name: Build project
              run: npm run build

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v2
              with:
                  name: production-files
                  path: ./dist

    build:
        name:
          build
        runs-on: ubuntu-latest
          steps:
              - name: Checkout
                uses: actions/checkout@v2

                  - name: Setup Node
                    uses: actions/setup-node@v1
                    with:
                      node-version: '18.x'
                  - name: Build project
                      run: npm run build

                  - name: Upload production-ready build files
                    uses: actions/upload-artifact@v2
                      with:
                        name: production-files
                        path: ./dist


    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy to GitHub Pages
                uses: peaceiris/github-pages-deploy-action@releases/v3
                with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
